name: projectgetx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/header.png
    - assets/logo_mcd.png
    - assets/mcdeliver.png
    - assets/sim.png
    - assets/menu_page.png
    - assets/bubur.png
    - assets/gulai.png
    - assets/hotcakes.png
    - assets/mcflurry.png
    - assets/cheeseburger.png
    - assets/kentang.png
    - assets/search.png
    - assets/pfp.png
    - assets/lines.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit.ttf
        - asset: assets/fonts/OutfitRegular.ttf
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700

